"""Central registry of all 16 NexusOS AI agents."""

AGENT_REGISTRY = [
    {
        "agent_id": "ceo",
        "name": "CEO Orchestrator",
        "department": "Executive",
        "icon": "🎯",
        "description": "Strategic planning, revenue optimization, cross-agent coordination, and business simulations.",
        "schedule": "Daily 03:00",
        "capabilities": ["strategy", "planning", "coordination", "simulation"],
        "default_status": "idle",
    },
    {
        "agent_id": "product_research",
        "name": "Product Research",
        "department": "Merchandising",
        "icon": "🔍",
        "description": "Winning product discovery, trend analysis, competitor monitoring, demand scoring.",
        "schedule": "Daily 06:00",
        "capabilities": ["research", "scoring", "trends", "competitor_analysis"],
        "default_status": "idle",
    },
    {
        "agent_id": "supplier",
        "name": "Supplier Agent",
        "department": "Operations",
        "icon": "📦",
        "description": "CJ Dropshipping integration, supplier validation, shipping analysis, stock monitoring.",
        "schedule": "Daily 07:00",
        "capabilities": ["cj_dropshipping", "validation", "shipping", "stock"],
        "default_status": "idle",
    },
    {
        "agent_id": "store_designer",
        "name": "Store Designer",
        "department": "Storefront",
        "icon": "🎨",
        "description": "Shopify theme customization, landing pages, product pages, UX/conversion optimization.",
        "schedule": "on-demand",
        "capabilities": ["shopify_cli", "theme", "landing_pages", "ux_optimization"],
        "default_status": "idle",
    },
    {
        "agent_id": "content",
        "name": "Content Writer",
        "department": "Creative",
        "icon": "✍️",
        "description": "Product descriptions, SEO blogs, ad copy, social captions, email, hooks, sales copy.",
        "schedule": "Weekly",
        "capabilities": ["copywriting", "seo", "email", "hooks"],
        "default_status": "idle",
    },
    {
        "agent_id": "ugc_creative",
        "name": "UGC Creative",
        "department": "Creative",
        "icon": "🎬",
        "description": "AI UGC videos, TikTok/Reels content, product demos, voiceovers, viral editing.",
        "schedule": "Tue/Fri 09:00",
        "capabilities": ["ugc_video", "tiktok", "reels", "voiceover"],
        "default_status": "idle",
    },
    {
        "agent_id": "image_gen",
        "name": "Image Generator",
        "department": "Creative",
        "icon": "🖼️",
        "description": "Product mockups, ad creatives, brand assets, logos, banners, social graphics.",
        "schedule": "on-demand",
        "capabilities": ["stable_diffusion", "mockups", "logos", "banners"],
        "default_status": "idle",
    },
    {
        "agent_id": "video_gen",
        "name": "Video Generator",
        "department": "Creative",
        "icon": "🎥",
        "description": "AI video generation, ad editing, subtitles, transitions, viral-style editing.",
        "schedule": "on-demand",
        "capabilities": ["video_generation", "editing", "subtitles", "ffmpeg"],
        "default_status": "idle",
    },
    {
        "agent_id": "marketing",
        "name": "Marketing Operator",
        "department": "Growth",
        "icon": "📣",
        "description": "Meta/TikTok/Google Ads, budget allocation, creative testing, audience analysis.",
        "schedule": "Daily 08:00",
        "capabilities": ["meta_ads", "tiktok_ads", "google_ads", "budget"],
        "default_status": "idle",
    },
    {
        "agent_id": "analytics",
        "name": "Analytics Agent",
        "department": "Data",
        "icon": "📊",
        "description": "KPI tracking, revenue analysis, forecasting, business intelligence, causation.",
        "schedule": "Hourly",
        "capabilities": ["kpis", "forecasting", "bi", "causation"],
        "default_status": "idle",
    },
    {
        "agent_id": "customer_support",
        "name": "Customer Support",
        "department": "Support",
        "icon": "💬",
        "description": "Ticket automation, FAQ handling, sentiment analysis, refund workflows.",
        "schedule": "Hourly",
        "capabilities": ["tickets", "faq", "sentiment", "refunds"],
        "default_status": "idle",
    },
    {
        "agent_id": "finance",
        "name": "Finance Agent",
        "department": "Finance",
        "icon": "💰",
        "description": "Profit analysis, cost tracking, unit economics, forecasting, cash flow.",
        "schedule": "Daily 04:00",
        "capabilities": ["profit", "unit_economics", "forecasting", "cashflow"],
        "default_status": "idle",
    },
    {
        "agent_id": "automation",
        "name": "Automation Builder",
        "department": "Ops",
        "icon": "⚙️",
        "description": "Workflow generation, trigger systems, scheduled ops, cross-agent orchestration.",
        "schedule": "on-demand",
        "capabilities": ["workflows", "triggers", "scheduling", "orchestration"],
        "default_status": "idle",
    },
    {
        "agent_id": "experimentation",
        "name": "Experimentation",
        "department": "Growth",
        "icon": "🧪",
        "description": "A/B testing, funnel testing, creative testing, offer optimization.",
        "schedule": "Weekly",
        "capabilities": ["ab_testing", "funnel", "creative_testing", "offers"],
        "default_status": "idle",
    },
    {
        "agent_id": "learning",
        "name": "Learning Agent",
        "department": "AI Ops",
        "icon": "🧠",
        "description": "Learns from outcomes, improves prompts/workflows/decisions, optimizes continuously.",
        "schedule": "Daily 21:00",
        "capabilities": ["learning", "prompt_optimization", "feedback_loops"],
        "default_status": "idle",
    },
    {
        "agent_id": "compliance",
        "name": "Compliance & Risk",
        "department": "Risk",
        "icon": "🛡️",
        "description": "Fraud analysis, platform policy monitoring, risk scoring, approval recommendations.",
        "schedule": "Daily 05:00",
        "capabilities": ["fraud", "policy", "risk_scoring", "compliance"],
        "default_status": "idle",
    },
]


def get_agent_definition(agent_id: str) -> dict | None:
    return next((a for a in AGENT_REGISTRY if a["agent_id"] == agent_id), None)
